export const SKILL_CATEGORIES = {
  languages: [
    "javascript", "typescript", "python", "java", "c++", "c#", "go", "rust",
    "ruby", "php", "swift", "kotlin", "scala", "r", "matlab", "c", "sql",
  ],
  frontend: [
    "react", "next.js", "nextjs", "vue", "angular", "html", "css", "tailwind",
    "sass", "redux", "webpack", "vite", "bootstrap", "material ui", "figma",
  ],
  backend: [
    "node.js", "nodejs", "express", "django", "flask", "fastapi", "spring",
    "spring boot", ".net", "laravel", "graphql", "rest api", "microservices",
    "kafka", "rabbitmq", "api design",
  ],
  databases: [
    "mysql", "postgresql", "mongodb", "redis", "elasticsearch", "dynamodb",
    "firebase", "sqlite", "oracle", "cassandra", "supabase",
  ],
  cloud: [
    "aws", "azure", "gcp", "google cloud", "docker", "kubernetes", "terraform",
    "ci/cd", "jenkins", "github actions", "devops", "linux", "nginx", "vercel",
  ],
  data: [
    "machine learning", "deep learning", "tensorflow", "pytorch", "pandas",
    "numpy", "scikit-learn", "data analysis", "nlp", "computer vision",
    "tableau", "power bi", "data science", "etl", "spark",
  ],
  tools: [
    "git", "github", "gitlab", "jira", "postman", "vs code", "intellij",
    "selenium", "cypress", "jest", "maven", "gradle",
  ],
  soft: [
    "leadership", "communication", "teamwork", "problem solving", "agile",
    "scrum", "project management", "collaboration", "mentoring", "analytical",
  ],
} as const;

export const SKILL_ALIASES: Record<string, string[]> = {
  javascript: ["js", "ecmascript"],
  typescript: ["ts"],
  "node.js": ["nodejs", "node js"],
  "next.js": ["nextjs", "next js"],
  "spring boot": ["springboot"],
  "rest api": ["restful", "rest apis", "api development"],
  "machine learning": ["ml"],
  "deep learning": ["dl"],
  postgresql: ["postgres"],
  kubernetes: ["k8s"],
  "ci/cd": ["cicd", "ci cd"],
  "github actions": ["gh actions"],
  "power bi": ["powerbi"],
  "vs code": ["vscode", "visual studio code"],
  "scikit-learn": ["sklearn"],
};

export const ALL_SKILLS = Object.values(SKILL_CATEGORIES).flat();

export const ROLE_PROFILES = [
  { role: "Frontend Developer", skills: ["react", "javascript", "typescript", "css", "html", "next.js"] },
  { role: "Backend Developer", skills: ["java", "spring boot", "node.js", "python", "sql", "rest api"] },
  { role: "Full Stack Developer", skills: ["react", "node.js", "javascript", "postgresql", "docker", "aws"] },
  { role: "Data Scientist", skills: ["python", "machine learning", "pandas", "sql", "tensorflow", "data analysis"] },
  { role: "DevOps Engineer", skills: ["aws", "docker", "kubernetes", "terraform", "ci/cd", "linux"] },
  { role: "Mobile Developer", skills: ["kotlin", "swift", "react", "java", "firebase"] },
] as const;

export const JOB_LISTINGS = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Razorpay",
    location: "Bangalore · Hybrid",
    type: "Full-time",
    salary: "₹28–42 LPA",
    posted: "2 days ago",
    experience: "4+ years",
    description: "Build payment dashboards with React, TypeScript, and Next.js. Strong CSS, performance optimization, and REST API integration.",
    requiredSkills: ["react", "typescript", "next.js", "javascript", "css", "rest api"],
    preferredSkills: ["redux", "webpack", "git"],
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Flipkart",
    location: "Bangalore",
    type: "Full-time",
    salary: "₹18–30 LPA",
    posted: "1 week ago",
    experience: "2–5 years",
    description: "E-commerce platform using Node.js, React, and PostgreSQL. Microservices, Docker, and AWS experience preferred.",
    requiredSkills: ["node.js", "react", "postgresql", "javascript", "rest api"],
    preferredSkills: ["docker", "aws", "microservices", "git"],
  },
  {
    id: "3",
    title: "Machine Learning Engineer",
    company: "Swiggy",
    location: "Bangalore · Remote",
    type: "Full-time",
    salary: "₹25–40 LPA",
    posted: "3 days ago",
    experience: "3+ years",
    description: "ML models for demand forecasting and recommendations. Python, TensorFlow/PyTorch, SQL required.",
    requiredSkills: ["python", "machine learning", "sql", "pandas"],
    preferredSkills: ["tensorflow", "pytorch", "aws", "nlp"],
  },
  {
    id: "4",
    title: "Backend Engineer",
    company: "PhonePe",
    location: "Pune",
    type: "Full-time",
    salary: "₹20–35 LPA",
    posted: "5 days ago",
    experience: "3+ years",
    description: "Scalable APIs with Java/Spring Boot and Kafka. Strong DSA and system design fundamentals.",
    requiredSkills: ["java", "spring boot", "sql", "rest api"],
    preferredSkills: ["kafka", "microservices", "docker", "aws"],
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "Zerodha",
    location: "Bangalore",
    type: "Full-time",
    salary: "₹22–38 LPA",
    posted: "4 days ago",
    experience: "3+ years",
    description: "Cloud infrastructure on AWS/GCP. Kubernetes, Terraform, CI/CD pipelines, and monitoring.",
    requiredSkills: ["aws", "docker", "kubernetes", "linux", "ci/cd"],
    preferredSkills: ["terraform", "jenkins", "github actions"],
  },
  {
    id: "6",
    title: "Data Analyst",
    company: "CRED",
    location: "Bangalore · Hybrid",
    type: "Full-time",
    salary: "₹12–22 LPA",
    posted: "1 day ago",
    experience: "1–3 years",
    description: "User behavior and product metrics analysis. SQL, Python, Tableau/Power BI required.",
    requiredSkills: ["sql", "python", "data analysis"],
    preferredSkills: ["tableau", "power bi", "excel", "communication"],
  },
  {
    id: "7",
    title: "React Native Developer",
    company: "Ola",
    location: "Bangalore",
    type: "Full-time",
    salary: "₹16–28 LPA",
    posted: "6 days ago",
    experience: "2+ years",
    description: "Build mobile apps for millions of users. React Native, JavaScript, and REST API experience.",
    requiredSkills: ["react", "javascript", "rest api", "git"],
    preferredSkills: ["typescript", "redux", "firebase"],
  },
  {
    id: "8",
    title: "Python Developer",
    company: "Freshworks",
    location: "Chennai · Hybrid",
    type: "Full-time",
    salary: "₹14–26 LPA",
    posted: "3 days ago",
    experience: "2–4 years",
    description: "Backend services with Python, FastAPI/Django. PostgreSQL and cloud deployment experience.",
    requiredSkills: ["python", "sql", "rest api", "git"],
    preferredSkills: ["fastapi", "django", "docker", "aws"],
  },
  {
    id: "9",
    title: "Cloud Engineer",
    company: "Infosys",
    location: "Hyderabad",
    type: "Full-time",
    salary: "₹15–28 LPA",
    posted: "1 week ago",
    experience: "2+ years",
    description: "Design and manage cloud solutions on AWS/Azure. IaC with Terraform, containerization.",
    requiredSkills: ["aws", "docker", "linux", "terraform"],
    preferredSkills: ["kubernetes", "azure", "ci/cd", "python"],
  },
  {
    id: "10",
    title: "SDE Intern → Full Time",
    company: "Amazon",
    location: "Bangalore",
    type: "Full-time",
    salary: "₹18–24 LPA",
    posted: "2 days ago",
    experience: "0–2 years",
    description: "Strong DSA, problem solving. Any one of Java, Python, or C++. System design basics.",
    requiredSkills: ["java", "python", "problem solving", "data structures"],
    preferredSkills: ["aws", "sql", "git", "communication"],
  },
] as const;
